image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build_image:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG --build-arg GIT_URL=$GIT_URL .
    - docker push $IMAGE_TAG
  artifacts:
    paths:
      - /git/fwb-daten
services:
- docker:dind
