image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"

build_image:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $DOCKER_IMAGE --build-arg GIT_URL=$GIT_URL .
  - docker push $DOCKER_IMAGE

services:
- docker:dind

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

sast:
  stage: test
