version: '3.8'

services:
  solr:
    image: docker.gitlab.gwdg.de/subugoe/adw/fwb-solr:main

  gitclone:
    build: gitclone
    volumes:
      - ./gitclone/git:/git
    env_file:
      - docker.env

  importer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9090:8080"
    volumes:
      - ./gitclone/git:/git
      - ./import-files:/import-files
    environment:
      - GIT_INPUT_DIR=/git/fwb-daten
      - OUTPUT_DIR=/import-files
      - SOLR_IMPORT_CORE=fwboffline
      - SOLR_ONLINE_CORE=fwb
    env_file:
      - docker.env
