version: '3.8'

services:
  solr:
    image: docker.gitlab.gwdg.de/subugoe/adw/fwb-solr:main

  importer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_URL: ${GIT_URL}
    restart: unless-stopped
    links:
      - mail
    ports:
      - "9090:8080"
    environment:
      - GIT_INPUT_DIR=/git/fwb-daten
      - OUTPUT_DIR=/import-files
      - SOLR_IMPORT_CORE=fwboffline
      - SOLR_ONLINE_CORE=fwb
    env_file:
      - docker.env
  mail:
    image: mailhog/mailhog
    ports:
      - "9091:8025"
